### ISSUE TITLE
[python-rhsm] Global socket timeout is set to 60sec after working with YumBase object

### ISSUE THREAD

**Issue by matpuk** [candlepin/subscription-manager#1006]
Steps to reproduce:

Just run the script on any EL5, EL6 or EL7 host:
```
import socket
import yum

yb = yum.YumBase()

print socket.getdefaulttimeout()
yb.getReposFromConfig()
print socket.getdefaulttimeout()
```

Actual result:
None
60.0

Expected result:
None
None

In real life this means that any complex app (or another Yum plugin) which uses yum module and then communicating with remote hosts using standard libraries like httplib, xmlrpc, etc. will encounter socket.TimeoutError while waiting for response if request processing takes more than 60sec.

See https://github.com/candlepin/python-rhsm/blob/master/src/rhsm/connection.py line 42.

**Comment by alikins** [comment]
I think the code in connection.py meant to only set a default timeout on python 2.3 (aka, RHEL5), but
that is not what it is doing...

```
if sys.version_info[0] == 2 and sys.version_info[0] <= 4:
```

should be
```
if sys.version_info[0] == 2 and sys.version_info[1] <= 4:
```
It's only looking at the major version, which is always 2, and always less than 4. 

[Not that setting a process wide default socket timeout is particular friendly, even on RHEL5.
And even on RHEL5, I'm not really sure why it needs to be changed. I think that may date back to attempts to work around proxies that would hold open connections on auth failure vs returning errors and closing socket (iirc, several large proxy providers in China did this). 

That's not a great reason to change that, especially for gui side with native event loop and timer callbacks. ]

That code needs to be removed.

**Comment by alikins** [comment]
Downstream bug created at https://bugzilla.redhat.com/show_bug.cgi?id=1195446

**Comment by alikins** [comment]
Potential partial fix at https://github.com/candlepin/python-rhsm/pull/144

The setdefaulttimeout() needs to be removed entirely, but that at least makes it python 2.3, and not at module scope for now.

**Comment by belonesox** [comment]
Why setdefaulttimeout() needs to be removed entirely?

I have opposite issue → infinite hangout (>12 hours) on SM to candlepin connection, because not default timeout set.

Stack:

        #6 <built-in function ssl_connect>
        #8 file '/usr/lib64/python2.6/site-packages/M2Crypto/SSL/Connection.py', in 'connect_ssl'
        #11 file '/usr/lib64/python2.6/site-packages/M2Crypto/SSL/Connection.py', in 'connect'
        #14 file '/usr/lib64/python2.6/site-packages/M2Crypto/httpslib.py', in 'connect'
        #17 file '/usr/lib64/python2.6/httplib.py', in 'send'
        #20 file '/usr/lib64/python2.6/httplib.py', in '_send_output'
        #23 file '/usr/lib64/python2.6/httplib.py', in 'endheaders'
        #26 file '/usr/lib64/python2.6/httplib.py', in '_send_request'
        #29 file '/usr/lib64/python2.6/httplib.py', in 'request'
        #33 file '/usr/lib64/python2.6/site-packages/rhsm/connection.py', in '_request'
        #37 file '/usr/lib64/python2.6/site-packages/rhsm/connection.py', in 'request_get'
        #40 file '/usr/lib64/python2.6/site-packages/rhsm/connection.py', in 'getStatus'
        #43 file '/usr/share/rhsm/subscription_manager/utils.py', in 'get_server_versions'
        #47 file '/usr/share/rhsm/subscription_manager/managercli.py', in 'log_server_version'
        #50 file '/usr/share/rhsm/subscription_manager/managercli.py', in 'main'
        #54 file '/usr/share/rhsm/subscription_manager/cli.py', in 'main'
        #62 file '/usr/share/rhsm/subscription_manager/managercli.py', in 'main'
        #65 file '/usr/sbin/subscription-manager', in 'main'
        #68 file '/usr/sbin/subscription-manager', in '<module>'
        
        (gdb) bt
        #0  0x00007f858ca0f810 in __read_nocancel () at ../sysdeps/unix/syscall-template.S:82
        #1  0x00007f858458afb1 in ?? () from /usr/lib64/libcrypto.so.10
        #2  0x00007f8584589309 in BIO_read () from /usr/lib64/libcrypto.so.10
        #3  0x00007f85848c1873 in ssl23_read_bytes () from /usr/lib64/libssl.so.10
        #4  0x00007f85848c07be in ssl23_connect () from /usr/lib64/libssl.so.10
        #5  0x00007f8582a8b973 in ssl_connect () from /usr/lib64/python2.6/site-packages/M2Crypto/__m2crypto.so
        #6  0x00007f8582a98b3b in ?? () from /usr/lib64/python2.6/site-packages/M2Crypto/__m2crypto.so
        #7  0x00007f858ccf39d4 in call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:3794

Why no default timeout?

http://wiki.4intra.net/User:StasFomin/Bugs/SubscriptionManager/Timeout

**Comment by awood** [comment]
This issue was addressed in [python-rhsm PR 170](https://github.com/candlepin/python-rhsm/pull/170)
