### ISSUE TITLE
subscription-manager COPR issue

### ISSUE THREAD

**Issue by jberanek** [candlepin/subscription-manager#1344]
Just got to the bottom of an issue with a Katello installation, and it appears to be down to the subscription-manager COPR repository for CentOS 6.

This repository has 2 duplicate RPMs for python-rhsm-1.16.2-1.el6.x86_64.rpm, but with different content/sha256 sums.

What this means is that the Katello instance downloads both packages, then manages to build repo files which refer to one RPM, but have the sha256 sum for the other package. :(

What this leads to is the following error from Yum:

```text
Downloading Packages:
python-rhsm-1.16.2-1.el6.x86_64.rpm                                                                                                   | 115 kB     00:00
https://katello.example.com/pulp/repos/Company/Library/CentOS-6/custom/CentOS/Subscription-Manager-CentOS-6-x86_64/python-rhsm-1.16.2-1.el6.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=Company_CentOS_Subscription-Manager-CentOS-6-x86_64 clean metadata
Trying other mirror.
...
Error Downloading Packages:
  python-rhsm-1.16.2-1.el6.x86_64: failure: python-rhsm-1.16.2-1.el6.x86_64.rpm from Company_CentOS_Subscription-Manager-CentOS-6-x86_64: [Errno 256] No more mirrors to try.
```

Is it possible to remove the earlier version of python-rhsm-1.16.2-1.el6.x86_64.rpm from the COPR repository, namely the one with build ID 00112618 ?

These are the 2 builds of python-rhsm with the same version number:

    $ sha256sum 00112618/python-rhsm-1.16.2-1.el6.x86_64.rpm 00129867/python-rhsm-1.16.2-1.el6.x86_64.rpm
    aeb8448489950a7811ca0bb3fbea0062ff5d7ee2799b4e058864af29c0a36521  00112618/python-rhsm-1.16.2-1.el6.x86_64.rpm
    3bd98e9cbfd7f29e0f64501f7d798cf07b6f25d6d9b276690b47cef25bbf5182  00129867/python-rhsm-1.16.2-1.el6.x86_64.rpm

**Comment by awood** [comment]
Hi,

I removed some of the builds and hopefully everything should be good now.  If you wouldn't mind running a `yum clean all` and then retrying, I think the issue should be fixed.
